- src: https://github.com/CiscoDevNet/ansible-pyats
  scm: git
  name: ansible-pyats

- name: parse_genie
  src: https://github.com/clay584/parse_genie
  scm: git
  version: master

# ansible-galaxy install -r requirements.yml