---
# ansible-rulebook --rulebook rulebooks/bgp-max-pfx-rulebook.yml -i cml_hosts.yml --verbose
# ansible-rulebook --rulebook rulebooks/bgp-max-pfx-rulebook.yml -i netbox_inventory.yml --verbose
# ansible-rulebook --rulebook rulebooks/bgp-max-pfx-rulebook.yml -i neox_inventory.yml --verbose --print-events
- name: Listen Kafka Events for BGP Neighbors
  hosts: all
  sources:
  - ansible.eda.kafka:
      host: devnetbox
      port: 9092
      topic: cisco-telemetry
      group_id: ansible-eda
      offset: latest
      verify_mode: CERT_NONE

  rules:
    - name: Display Kafka Logs and Run Action Playbook
      # for ioxr BGP neighbor down due to prefix limit exceeded
      condition: events.body.fields.is_neighbor_max_prefix_shutdown == "true" and events.body.fields.reset_reason == "max-prefix-exceeded"
      action:
        run_playbook:
          # name: playbooks/bgp-max-pfx-fix.yml
          name: playbooks/bgp-max-pfx-vault.yml
          extra_vars:
            target_host: "{{ event.body.tags.source }}"
            bgp_neighbor: "{{ event.body.tags.neighbor_address }}"
            bgp_remote_asn: "{{ event.body.fields.remote_as_number }}"
            bgp_local_asn: "{{ event.body.fields.local_as }}"
          verbosity: 1
          copy_files: True

    - name: Reason for BGP State Down
      condition: events.body.fields.open_check_error_code == "neighbor-down"
      action:
        debug:
          msg: |
            **Device: {{ event.body.tags.source }} 
            **BGP Neighbor: {{ event.body.tags.neighbor_address }}
            **Description: {{ event.body.fields.description | default('N/A') }}
            **Remote ASN: {{ event.body.fields.remote_as_number }}
            **Address Family: {{ event.body.fields['af_data/af_name']}}
            **Prefix Limit: {{ event.body.fields['af_data/max_prefix_limit'] }}
            **Prefix Limit Threshold: {{ event.body.fields['af_data/max_prefix_threshold_percent'] }}
            **Reason: {{ event.body.fields.reset_reason }}