version: '3.7'

services:
  vault:
    image: vault:1.13.3
    container_name: vault-server
    volumes:
      - ./vault_config:/vault/config
      - ./vault_data:/vault/file
      - ./vault_logs:/vault/logs
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_API_ADDR: http://0.0.0.0:8200
    networks:
      - vault_network
    cap_add:
      - IPC_LOCK
    command: server 
    restart: always

networks:
  vault_network:
    external: true

#### config.hcl ####
# # Configure listener
# listener "tcp" {
#   address       = "0.0.0.0:8200"
#   tls_disable   = true
# }

# # Configures the storage backend where Vault data is stored, local or consul
# storage "file" {
#   path  = "/vault/data"
# }

# # Disables all caches within Vault
# disable_cache = true

# # Disables the server from executing the mlock
# disable_mlock = true

# # Location for vault log file
# log_file = "/vault/logs/vault.log" 

# # Vault API address
# api_addr = "http://0.0.0.0:8200" 

# # Enables the built-in web UI
# ui = true
